// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcvgidsazfbeqbkszqdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjdmdpZHNhemZiZXFia3N6cWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTg0NTYsImV4cCI6MjA3NDM3NDQ1Nn0.x0wVPxA18V1yVkjRG9BZScy3OyNUrTQHHTjpJf_ynic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});